version: '3.7'

services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pretorean
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - project

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - project

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./../scrypted_med:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  dart:
    build: ./
    ports:
      - 8888:80
    depends_on:
      - postgres
    networks:
      - project

networks:
  project:
    driver: bridge
